name: flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
          channel: "stable"

      - name: flutter version
        run: flutter --version

      - name: flutter analyze
        run: flutter analyze